// Database types for Supabase
// This file will be auto-generated by Supabase CLI, but we define the structure here

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export interface Database {
  public: {
    Tables: {
      users: {
        Row: {
          id: string;
          email: string;
          full_name: string;
          role_id: string;
          department_id: string | null;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          email: string;
          full_name: string;
          role_id: string;
          department_id?: string | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          email?: string;
          full_name?: string;
          role_id?: string;
          department_id?: string | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      roles: {
        Row: {
          id: string;
          name: string;
          display_name: string;
          description: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          display_name: string;
          description?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          display_name?: string;
          description?: string | null;
          created_at?: string;
        };
      };
      departments: {
        Row: {
          id: string;
          code: string;
          name: string;
          description: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          code: string;
          name: string;
          description?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          code?: string;
          name?: string;
          description?: string | null;
          created_at?: string;
        };
      };
      tickets: {
        Row: {
          id: string;
          ticket_code: string;
          ticket_type: string;
          status: string;
          priority: string;
          subject: string;
          description: string | null;
          department_id: string;
          created_by: string;
          assigned_to: string | null;
          rfq_data: Json | null;
          created_at: string;
          updated_at: string;
          resolved_at: string | null;
          closed_at: string | null;
        };
        Insert: {
          id?: string;
          ticket_code: string;
          ticket_type: string;
          status?: string;
          priority?: string;
          subject: string;
          description?: string | null;
          department_id: string;
          created_by: string;
          assigned_to?: string | null;
          rfq_data?: Json | null;
          created_at?: string;
          updated_at?: string;
          resolved_at?: string | null;
          closed_at?: string | null;
        };
        Update: {
          id?: string;
          ticket_code?: string;
          ticket_type?: string;
          status?: string;
          priority?: string;
          subject?: string;
          description?: string | null;
          department_id?: string;
          created_by?: string;
          assigned_to?: string | null;
          rfq_data?: Json | null;
          created_at?: string;
          updated_at?: string;
          resolved_at?: string | null;
          closed_at?: string | null;
        };
      };
      ticket_assignments: {
        Row: {
          id: string;
          ticket_id: string;
          assigned_to: string;
          assigned_by: string;
          assigned_at: string;
          notes: string | null;
        };
        Insert: {
          id?: string;
          ticket_id: string;
          assigned_to: string;
          assigned_by: string;
          assigned_at?: string;
          notes?: string | null;
        };
        Update: {
          id?: string;
          ticket_id?: string;
          assigned_to?: string;
          assigned_by?: string;
          assigned_at?: string;
          notes?: string | null;
        };
      };
      sla_config: {
        Row: {
          id: string;
          department_id: string;
          ticket_type: string;
          first_response_hours: number;
          resolution_hours: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          department_id: string;
          ticket_type: string;
          first_response_hours?: number;
          resolution_hours?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          department_id?: string;
          ticket_type?: string;
          first_response_hours?: number;
          resolution_hours?: number;
          created_at?: string;
          updated_at?: string;
        };
      };
      sla_tracking: {
        Row: {
          id: string;
          ticket_id: string;
          first_response_at: string | null;
          first_response_sla_hours: number;
          first_response_met: boolean | null;
          resolution_at: string | null;
          resolution_sla_hours: number;
          resolution_met: boolean | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          ticket_id: string;
          first_response_at?: string | null;
          first_response_sla_hours: number;
          first_response_met?: boolean | null;
          resolution_at?: string | null;
          resolution_sla_hours: number;
          resolution_met?: boolean | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          ticket_id?: string;
          first_response_at?: string | null;
          first_response_sla_hours?: number;
          first_response_met?: boolean | null;
          resolution_at?: string | null;
          resolution_sla_hours?: number;
          resolution_met?: boolean | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      ticket_comments: {
        Row: {
          id: string;
          ticket_id: string;
          user_id: string;
          content: string;
          is_internal: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          ticket_id: string;
          user_id: string;
          content: string;
          is_internal?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          ticket_id?: string;
          user_id?: string;
          content?: string;
          is_internal?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      audit_logs: {
        Row: {
          id: string;
          table_name: string;
          record_id: string;
          action: string;
          old_data: Json | null;
          new_data: Json | null;
          user_id: string;
          ip_address: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          table_name: string;
          record_id: string;
          action: string;
          old_data?: Json | null;
          new_data?: Json | null;
          user_id: string;
          ip_address?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          table_name?: string;
          record_id?: string;
          action?: string;
          old_data?: Json | null;
          new_data?: Json | null;
          user_id?: string;
          ip_address?: string | null;
          created_at?: string;
        };
      };
      rate_quotes: {
        Row: {
          id: string;
          ticket_id: string;
          quote_number: string;
          amount: number;
          currency: string;
          valid_until: string;
          terms: string | null;
          status: string;
          created_by: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          ticket_id: string;
          quote_number: string;
          amount: number;
          currency?: string;
          valid_until: string;
          terms?: string | null;
          status?: string;
          created_by: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          ticket_id?: string;
          quote_number?: string;
          amount?: number;
          currency?: string;
          valid_until?: string;
          terms?: string | null;
          status?: string;
          created_by?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      ticket_attachments: {
        Row: {
          id: string;
          ticket_id: string;
          file_name: string;
          file_url: string;
          file_type: string;
          file_size: number;
          uploaded_by: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          ticket_id: string;
          file_name: string;
          file_url: string;
          file_type: string;
          file_size: number;
          uploaded_by: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          ticket_id?: string;
          file_name?: string;
          file_url?: string;
          file_type?: string;
          file_size?: number;
          uploaded_by?: string;
          created_at?: string;
        };
      };
      ticket_sequences: {
        Row: {
          id: string;
          ticket_type: string;
          department_code: string;
          date_key: string;
          last_sequence: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          ticket_type: string;
          department_code: string;
          date_key: string;
          last_sequence?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          ticket_type?: string;
          department_code?: string;
          date_key?: string;
          last_sequence?: number;
          created_at?: string;
          updated_at?: string;
        };
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      generate_ticket_code: {
        Args: {
          p_ticket_type: string;
          p_department_code: string;
        };
        Returns: string;
      };
      get_user_role: {
        Args: {
          user_id: string;
        };
        Returns: string;
      };
      get_user_department: {
        Args: {
          user_id: string;
        };
        Returns: string;
      };
    };
    Enums: {
      [_ in never]: never;
    };
  };
}